#!/bin/bash -e
#$ -wd /path/to/directory
#$ -pe smp 1-8
#$ -l h_vmem=1.5G
#$ -N scenario_1
#$ -j y
#$ -M #EMAIL
#$ -m ea
#$ -t 1-22

/share/apps/plink2 --bfile /path/to/file/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_PGCSCZ_overlap_noAmb --a1-/path/to/file/full_dataset_a1_update_v1.txt --allow-no-sex --make-bed --out /path/to/file/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_PGCSCZ_overlap_noAmb_a1_v1
