#!/bin/bash -e
#$ -wd /path/to/directory
#$ -pe smp 1-8
#$ -l h_vmem=5G
#$ -N update_full_dataset_A1_v4
#$ -j y
#$ -M #EMAIL
#$ -m ea
#$ -t 1-22



/share/apps/plink2 --bfile /path/to/file/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_COG_overlap_noAmb_a1_v1 --exclude /path/to/file/cog_v4_to_remove.txt --keep-allele-order --allow-no-sex --make-bed --out /path/to/file/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_COG_harmonized
