#!/bin/bash -e
#$ -wd /path/to/directory/
#$ -pe smp 1-8
#$ -l h_vmem=5G
#$ -N update_full_dataset_A1_v4
#$ -j y
#$ -M #EMAIL
#$ -m ea
#$ -t 1-22



/share/apps/plink2 --bfile /path/to/file/TWAS_PRS/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_COG_overlap_noAmb_a1_v1 --exclude /path/to/file/A1_A2_CLOZUK_full_dataset_PGCSCZ_to_remove.txt --keep-allele-order --allow-no-sex --make-bed --out /path/to/file/CLOZUK_GWAS_BGE_chr${SGE_TASK_ID}_full_dataset_rsID_QCd_COG_harmonized

## This creates .bim files harmonized to the cognition summary statistics from Savage et al. 2018
